#include<iostream>
#include<vector>
#include<string>
using namespace std;

int N;

int main(){
    int i;
    cin>>N;
    vector<string> vctr;
    vector<char> chr;
    vector<char> F;
    vector<char> L;
    int sum =0;
    char l,f;       
    string x;

    for(int i=0;i<N;i++){
        cin>>x;
    //    vctr.push_back(x);
        
        l = x[x.size()-1];
        f = x[0];
    
        L.push_back(l); 
        F.push_back(f); 
      }


    for(int i=0;i<N;i++){
        cin>>x;
    //    vctr.push_back(x);
        
        l = x[x.size()-1];
        f = x[0];
    
        L.push_back(l); 
        F.push_back(f); 
      }


      


    

    }





